TYPO3 10 LTS compatible
AOEpeople/TYPO3-varnish pull request #10
Opened 2021-05-21 11:40 UTC by tomasnorre

2021-05-25 13:14 UTC, tomasnorre commented on Classes/TYPO3/Hooks/BackendAjaxHook.php
> +        $this->varnish = $objectManager->get(Varnish::class);
I know that the ObjectManager->get() is deprecated, but haven't found a better way to do this in context of a Backend Hook. The GeneralUtility::makeInstance() isn't working in this context for the Varnish instance.

2021-05-26 08:37 UTC, TomSchenk approved these changes

2021-05-26 08:45 UTC, tlayh requested changes

2021-05-26 08:45 UTC, tlayh commented on Classes/TYPO3/Hooks/BackendAjaxHook.php
> +        $this->varnish = $objectManager->get(Varnish::class);
AbstractHook is using the variant with GeneralUtility::makeInstance(). Is it different there?

2021-05-26 08:45 UTC, tlayh commented on Classes/System/Http.php
> +use function GuzzleHttp\Promise\settle;
settle is deprecated. Is there some other way? Utils::settle ?

2021-05-26 08:45 UTC, tlayh commented on Tests/Unit/TYPO3/Hooks/ContentPostProcOutputHookTest.php
Some unused imports here.

2021-05-26 08:45 UTC, tlayh commented on Tests/Unit/TYPO3/Hooks/TceMainHookTest.php
>  use TYPO3\CMS\Extbase\Object\ObjectManagerInterface;
ObjectManagerInterface not used anymore

2021-05-27 09:03 UTC, tomasnorre commented on Classes/System/Http.php
> +use function GuzzleHttp\Promise\settle;
Yep. Didn't pay attention to this.

2021-05-27 09:16 UTC, merged